title: Muneem
permalink: pretty
tagline: One stop shop for creating beautiful quotations
url: https://www.muneemapp.com
author: Ayush Gupta
description: Create beautiful quotations, estimates, purchase orders and other documents for your business
sass:
  sass_dir: css
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
